### ISSUE TITLE
Reeller is not a constructor (using CDN)

### ISSUE THREAD

**Issue by PubliAlex** [Cuberto/reeller#3]
Hello,

I try to make Reeller to work using CDN, have gsap loaded etc....

Whatever I try, I always have the same error : "Reeller is not a constructor"

Best regards,

Alex

**Comment by Drafteed** [comment]
```js
const reller = new Reeller.Reeller();
```

**Comment by PubliAlex** [comment]
Hello,

Thank you for the answer, will try that, so the doc need to be updated : 

![image](https://github.com/Cuberto/reeller/assets/55833027/0a1918e7-f0f6-4c2a-a27d-62e0b7b76213)

**Comment by atulkadyan** [comment]
> Hello,
> 
> Thank you for the answer, will try that, so the doc need to be updated :
> 
> ![image](https://user-images.githubusercontent.com/55833027/255078031-0a1918e7-f0f6-4c2a-a27d-62e0b7b76213.png)

does it worked?

**Comment by Drafteed** [comment]
Doc fixed in a2f47b6
